version: "3"

services:
  backend:
    build: ./backend
    container_name: backend
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:test@db:5432/test
      # - DATABASE_URL=postgresql://my_user:my_password@postgresql-master:5432/my_database # com replicação
    volumes:
      - .:/home/node/app/
    depends_on:
      - db
      # - postgresql-master
    ports:
      - 3000:3000
    restart: unless-stopped

  auth:
    build: ./backend
    container_name: auth
    environment:
      - PORT=3001
      - DATABASE_URL=postgresql://postgres:test@db:5432/test
      # - DATABASE_URL=postgresql://my_user:my_password@postgresql-master:5432/my_database # com replicação
    volumes:
      - .:/home/node/app/
    depends_on:
      - db
      # - postgresql-master
    ports:
      - 3001:3001
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - .:/home/node/app/
    depends_on:
      - backend
    ports:
      - 4200:4200
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: [backend, auth, frontend]

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_PASSWORD: test
      $POSTGRES_USER: postgres
      $POSTGRES_DB: test
    ports:
      - 5432:5432
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
      # - ./.docker/postgres:/docker-entrypoint-initdb.d
    restart: unless-stopped

  # postgresql-master:
  #   image: 'bitnami/postgresql:latest'
  #   ports:
  #     - '5432'
  #   volumes:
  #     - 'postgresql_master_data:/bitnami/postgresql'
  #   environment:
  #     - POSTGRESQL_REPLICATION_MODE=master
  #     - POSTGRESQL_REPLICATION_USER=repl_user
  #     - POSTGRESQL_REPLICATION_PASSWORD=repl_password
  #     - POSTGRESQL_USERNAME=my_user
  #     - POSTGRESQL_PASSWORD=my_password
  #     - POSTGRESQL_DATABASE=my_database
  # postgresql-slave:
  #   image: 'bitnami/postgresql:latest'
  #   ports:
  #     - '5432'
  #   depends_on:
  #     - postgresql-master
  #   environment:
  #     - POSTGRESQL_REPLICATION_MODE=slave
  #     - POSTGRESQL_REPLICATION_USER=repl_user
  #     - POSTGRESQL_REPLICATION_PASSWORD=repl_password
  #     - POSTGRESQL_MASTER_HOST=postgresql-master
  #     - POSTGRESQL_PASSWORD=my_password
  #     - POSTGRESQL_MASTER_PORT_NUMBER=5432

# volumes:
#   postgresql_master_data: