version: "3"

services:
  backend:
    build: backend
    container_name: backend
    volumes:
      - .:/home/node/app/
    depends_on:
      - db
    ports:
      - 3000:3000
    restart: unless-stopped

  frontend:
    build: frontend
    container_name: frontend
    volumes:
      - .:/home/node/app/
    depends_on:
      - backend
    ports:
      - 8080:8080
    restart: unless-stopped

  # nginx:
  #   image: nginx
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - backend
  #     - frontend

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_PASSWORD: test
      $POSTGRES_USER: postgres
      $POSTGRES_DB: test
    ports:
      - 5432:5432
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
      - ./.docker/postgres:/docker-entrypoint-initdb.d
    restart: unless-stopped