version: "3"

services:
  web:
    build: frontend
    container_name: web
    volumes:
      - .:/home/node/app/
    depends_on:
      - backend
    ports:
      - 8080:8080

  backend:
    build: backend
    container_name: backend
    volumes:
      - .:/home/node/app/
    depends_on:
      - db
    ports:
      - 3000:3000

  # studio:
  #   build: .
  # container_name: studio
  #   depends_on:
  #     - postgres-db
  #   ports:
  #     - 5556:5556
  #   command: yarn studio

  nginx:
    image: nginx
    ports:
      - 80:80
    depends_on:
      - backend
      - web

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_PASSWORD: test
    ports:
      - 5432:5432
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
