version: "3"

services:
  backend:
    build: ./backend
    container_name: backend
    environment:
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:test@db:5432/test
    volumes:
      - .:/home/node/app/
    depends_on:
      - db
    ports:
      - 3000:3000
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: frontend
    volumes:
      - .:/home/node/app/
    depends_on:
      - backend
    ports:
      - 4200:4200
    restart: unless-stopped

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - 8080:80
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on: [backend, frontend]

  db:
    image: postgres:15
    container_name: db
    environment:
      POSTGRES_PASSWORD: test
      $POSTGRES_USER: postgres
      $POSTGRES_DB: test
    ports:
      - 5432:5432
    volumes:
      - ./.docker/dbdata:/var/lib/postgresql/data
      # - ./.docker/postgres:/docker-entrypoint-initdb.d
<<<<<<< HEAD
    restart: unless-stopped
=======
    restart: unless-stopped
>>>>>>> main
